### ISSUE TITLE
Noise dimensions in class CustomSingleTaskGP

### ISSUE THREAD

**Issue by carme-hp** [Lukuas31415/BA#2]
@Lukuas31415 I looked into getting `qMaxValueEntropy` to work. 

The error message says that there is a mismatch in the dimensions of the noise (defined in the gp model) with the training data (which is given implicitely in `optimize_acqf`). 

If I modify the noise dimensions by using `train_Yvar.unsqueeze(-1)`, then I get to successfully call `optimize_acqf` once.  However after the successful call I get an other noise mismatch (because the noise increases from (3,1,1) to (4,1,1).

Is there a reason for you to use GaussianLikelihood instead of FixedNoiseGaussianLikelihood? Maybe this makes it easier. 

You can check the code at branch noise-dimensions. Maybe this helps you further debug the problem.

**Comment by Lukuas31415** [comment]
@carme-hp I don't know anymore why I chose FixedNoiseGaussianLikelihood and not GaussianLikelihood. I just changed it and suddenly everything is working and I'm not even getting any warnings anymore. Thanks for the help, I wouldn't have found that!
